/**
 * mock-data.ts
 * Mock data for the Booking List feature.
 * Contains sample booking list items and booking details
 * for frontend demonstration without API integration.
 */

import type {
  BookingListItem,
  BookingDetailsResponse,
} from "@/types/DashboardTypes/BookingsTypes"

/** Mock booking list data for the table */
export const mockBookingListData: BookingListItem[] = [
  {
    booking_id: 1,
    display_booking_id: "#CH 565",
    player_name: "Imrul Hossain",
    player_id: 1,
    display_player_id: "#CN 256",
    player_email: "imrul@email.com",
    session_id: 1,
    session_name: "Weekend Warrior",
    field_name: "Toffie Fun World",
    match_date: "26 Jan 2026",
    booking_date: "2024-01-15",
    booking_flow: "online",
    match_type: "Social",
    team: "team_a",
    team_display: "Alpha Squad",
    player_count: 5,
    amount: "256.00",
    amount_display: "$256",
    package_name: "Beginner",
    check_in_status: "pending",
    payment_status: "paid",
    status: "pending",
    can_view: true,
  },
  {
    booking_id: 2,
    display_booking_id: "#CH 566",
    player_name: "Imrul Hossain",
    player_id: 2,
    display_player_id: "#CN 257",
    player_email: "imrul2@email.com",
    session_id: 1,
    session_name: "Weekend Warrior",
    field_name: "Toffie Fun World",
    match_date: "26 Jan 2026",
    booking_date: "2024-01-16",
    booking_flow: "online",
    match_type: "Social",
    team: "team_b",
    team_display: "Bravo Team",
    player_count: 4,
    amount: "256.00",
    amount_display: "$256",
    package_name: "Beginner",
    check_in_status: "pending",
    payment_status: "failed",
    status: "failed",
    can_view: true,
  },
  {
    booking_id: 3,
    display_booking_id: "#CH 567",
    player_name: "Imrul Hossain",
    player_id: 3,
    display_player_id: "#CN 258",
    player_email: "imrul3@email.com",
    session_id: 2,
    session_name: "Night Ops Match",
    field_name: "Toffie Fun World",
    match_date: "26 Jan 2026",
    booking_date: "2024-01-17",
    booking_flow: "walk_in",
    match_type: "Social",
    team: "team_a",
    team_display: "Shadow Unit",
    player_count: 6,
    amount: "256.00",
    amount_display: "$256",
    package_name: "Beginner",
    check_in_status: "pending",
    payment_status: "failed",
    status: "failed",
    can_view: true,
  },
  {
    booking_id: 4,
    display_booking_id: "#CH 568",
    player_name: "Imrul Hossain",
    player_id: 4,
    display_player_id: "#CN 259",
    player_email: "imrul4@email.com",
    session_id: 2,
    session_name: "Night Ops Match",
    field_name: "Toffie Fun World",
    match_date: "26 Jan 2026",
    booking_date: "2024-01-18",
    booking_flow: "online",
    match_type: "Social",
    team: "team_b",
    team_display: "Ghost Squad",
    player_count: 3,
    amount: "256.00",
    amount_display: "$256",
    package_name: "Beginner",
    check_in_status: "pending",
    payment_status: "failed",
    status: "failed",
    can_view: true,
  },
  {
    booking_id: 5,
    display_booking_id: "#CH 569",
    player_name: "Imrul Hossain",
    player_id: 5,
    display_player_id: "#CN 260",
    player_email: "imrul5@email.com",
    session_id: 3,
    session_name: "Tournament Qualifier",
    field_name: "Toffie Fun World",
    match_date: "26 Jan 2026",
    booking_date: "2024-01-19",
    booking_flow: "online",
    match_type: "Ranked",
    team: "team_a",
    team_display: "Elite Force",
    player_count: 8,
    amount: "256.00",
    amount_display: "$256",
    package_name: "Beginner",
    check_in_status: "check_in",
    payment_status: "paid",
    status: "paid",
    can_view: true,
  },
  {
    booking_id: 6,
    display_booking_id: "#CH 570",
    player_name: "Imrul Hossain",
    player_id: 6,
    display_player_id: "#CN 261",
    player_email: "imrul6@email.com",
    session_id: 3,
    session_name: "Tournament Qualifier",
    field_name: "Toffie Fun World",
    match_date: "26 Jan 2026",
    booking_date: "2024-01-20",
    booking_flow: "online",
    match_type: "Ranked",
    team: "team_b",
    team_display: "Rebel Alliance",
    player_count: 7,
    amount: "256.00",
    amount_display: "$256",
    package_name: "Beginner",
    check_in_status: "check_in",
    payment_status: "paid",
    status: "paid",
    can_view: true,
  },
  {
    booking_id: 7,
    display_booking_id: "#CH 571",
    player_name: "Imrul Hossain",
    player_id: 7,
    display_player_id: "#CN 262",
    player_email: "imrul7@email.com",
    session_id: 4,
    session_name: "Corporate Team Building",
    field_name: "Toffie Fun World",
    match_date: "26 Jan 2026",
    booking_date: "2024-01-21",
    booking_flow: "walk_in",
    match_type: "Ranked",
    team: "team_a",
    team_display: "Company A",
    player_count: 10,
    amount: "256.00",
    amount_display: "$256",
    package_name: "Beginner",
    check_in_status: "check_in",
    payment_status: "paid",
    status: "paid",
    can_view: true,
  },
  {
    booking_id: 8,
    display_booking_id: "#CH 572",
    player_name: "Imrul Hossain",
    player_id: 8,
    display_player_id: "#CN 263",
    player_email: "imrul8@email.com",
    session_id: 4,
    session_name: "Corporate Team Building",
    field_name: "Toffie Fun World",
    match_date: "26 Jan 2026",
    booking_date: "2024-01-22",
    booking_flow: "online",
    match_type: "Ranked",
    team: "team_b",
    team_display: "Company B",
    player_count: 9,
    amount: "256.00",
    amount_display: "$256",
    package_name: "Beginner",
    check_in_status: "check_in",
    payment_status: "paid",
    status: "paid",
    can_view: true,
  },
  {
    booking_id: 9,
    display_booking_id: "#CH 573",
    player_name: "Imrul Hossain",
    player_id: 9,
    display_player_id: "#CN 264",
    player_email: "imrul9@email.com",
    session_id: 5,
    session_name: "Pro League Practice",
    field_name: "Toffie Fun World",
    match_date: "26 Jan 2026",
    booking_date: "2024-01-23",
    booking_flow: "online",
    match_type: "Ranked",
    team: "team_a",
    team_display: "Pro Stars",
    player_count: 12,
    amount: "256.00",
    amount_display: "$256",
    package_name: "Beginner",
    check_in_status: "check_in",
    payment_status: "paid",
    status: "paid",
    can_view: true,
  },
  {
    booking_id: 10,
    display_booking_id: "#CH 574",
    player_name: "Imrul Hossain",
    player_id: 10,
    display_player_id: "#CN 265",
    player_email: "imrul10@email.com",
    session_id: 5,
    session_name: "Pro League Practice",
    field_name: "Toffie Fun World",
    match_date: "26 Jan 2026",
    booking_date: "2024-01-24",
    booking_flow: "walk_in",
    match_type: "Social",
    team: "team_b",
    team_display: "Rising Suns",
    player_count: 11,
    amount: "256.00",
    amount_display: "$256",
    package_name: "Beginner",
    check_in_status: "pending",
    payment_status: "pending",
    status: "pending",
    can_view: true,
  },
]

/** Mock booking details for the detail sheet */
export const mockBookingDetails: BookingDetailsResponse = {
  success: true,
  message: "Booking details retrieved successfully",
  meta: {},
  data: {
    booking: {
      id: 1,
      display_booking_id: "#CNH 565",
      status: "pending",
      payment_status: "failed",
      payment_reference: "TXN-2024-001",
      transaction_id: "#CNH 565",
      booking_flow: "online",
      team: "team_a",
      team_display: "Alpha Squad",
      player_count: 5,
      created_at: "2024-01-15",
      paid_at: "2024-01-15",
      confirmed_at: "2024-01-15",
      date_time: "02:30 AM, 25 jan 2026",
    },
    player: {
      id: 1,
      display_player_id: "#CN 256",
      full_name: "Imrul Hossain",
      email: "name@gmail.com",
      contact_number: "+26 256 2564",
      location: "New York, USA",
      profile_image: null,
    },
    session: {
      id: 1,
      session_name: "Imrul Hossain",
      field_name: "Toffie Fun World",
      match_type: "Ranked",
      package_name: "Beginner",
      session_visibility: "public",
      match_date: "25 January, 2026",
      start_time: "02:30 AM",
      end_time: "03:30 PM",
      team_a_name: "Alpha Squad",
      team_b_name: "Bravo Team",
      entry_fee: "25.00",
      status: "open",
    },
    payment: {
      entry_fee_total: "25.25",
      package_fee: "10.00",
      commission_rate: "5%",
      commission_amount: "05.25",
      net_profit: "24.05",
      total_amount: "25.25",
      total_amount_display: "$25.25",
      currency: "USD",
      payment_method: "PayPal",
    },
    package: {
      id: 1,
      package_name: "Beginner",
      package_fee: "10.00",
      description: "Basic equipment rental",
      include_items: ["Mask", "Gun", "50 Paintballs"],
    },
    selected_players: [
      {
        id: 1,
        full_name: "Imrul Hossain",
        email: "imrul@email.com",
        profile_image: null,
      },
      {
        id: 2,
        full_name: "Sarah Johnson",
        email: "sarah@email.com",
        profile_image: null,
      },
    ],
    session_booking: {
      id: 1,
      status: "pending",
      paid_amount: "25.25",
      payment_status: "failed",
    },
  },
  requestId: "req-001",
}
