/**
 * mock-data.ts
 * Mock data for the Booking List feature.
 * Contains sample booking list items and booking details
 * for frontend demonstration without API integration.
 */

import type {
  BookingListItem,
  BookingDetailsResponse,
} from "@/types/DashboardTypes/BookingListTypes"

/** Mock booking list data for the table */
export const mockBookingListData: BookingListItem[] = [
  {
    booking_id: 1,
    display_booking_id: "#BK 1001",
    player_name: "John Smith",
    player_id: 1,
    display_player_id: "#PL 2001",
    player_email: "john@email.com",
    session_id: 1,
    session_name: "Weekend Warrior",
    field_name: "Tactical Arena NYC",
    match_date: "2024-01-20",
    booking_date: "2024-01-15",
    booking_flow: "online",
    match_type: "Ranked",
    team: "team_a",
    team_display: "Alpha Squad",
    player_count: 5,
    amount: "125.00",
    amount_display: "$125.00",
    payment_status: "paid",
    status: "confirmed",
    can_view: true,
  },
  {
    booking_id: 2,
    display_booking_id: "#BK 1002",
    player_name: "Sarah Johnson",
    player_id: 2,
    display_player_id: "#PL 2002",
    player_email: "sarah@email.com",
    session_id: 1,
    session_name: "Weekend Warrior",
    field_name: "Tactical Arena NYC",
    match_date: "2024-01-20",
    booking_date: "2024-01-16",
    booking_flow: "online",
    match_type: "Social",
    team: "team_b",
    team_display: "Bravo Team",
    player_count: 4,
    amount: "100.00",
    amount_display: "$100.00",
    payment_status: "pending",
    status: "open",
    can_view: true,
  },
  {
    booking_id: 3,
    display_booking_id: "#BK 1003",
    player_name: "Mike Davis",
    player_id: 3,
    display_player_id: "#PL 2003",
    player_email: "mike@email.com",
    session_id: 2,
    session_name: "Night Ops Match",
    field_name: "Shadow Ops Center",
    match_date: "2024-01-22",
    booking_date: "2024-01-17",
    booking_flow: "walk_in",
    match_type: "Ranked",
    team: "team_a",
    team_display: "Shadow Unit",
    player_count: 6,
    amount: "150.00",
    amount_display: "$150.00",
    payment_status: "paid",
    status: "confirmed",
    can_view: true,
  },
  {
    booking_id: 4,
    display_booking_id: "#BK 1004",
    player_name: "Emily Brown",
    player_id: 4,
    display_player_id: "#PL 2004",
    player_email: "emily@email.com",
    session_id: 2,
    session_name: "Night Ops Match",
    field_name: "Shadow Ops Center",
    match_date: "2024-01-22",
    booking_date: "2024-01-18",
    booking_flow: "online",
    match_type: "Social",
    team: "team_b",
    team_display: "Ghost Squad",
    player_count: 3,
    amount: "75.00",
    amount_display: "$75.00",
    payment_status: "cancelled",
    status: "cancelled",
    can_view: true,
  },
  {
    booking_id: 5,
    display_booking_id: "#BK 1005",
    player_name: "Chris Wilson",
    player_id: 5,
    display_player_id: "#PL 2005",
    player_email: "chris@email.com",
    session_id: 3,
    session_name: "Tournament Qualifier",
    field_name: "Elite Paintball Grounds",
    match_date: "2024-01-25",
    booking_date: "2024-01-19",
    booking_flow: "online",
    match_type: "Ranked",
    team: "team_a",
    team_display: "Elite Force",
    player_count: 8,
    amount: "200.00",
    amount_display: "$200.00",
    payment_status: "paid",
    status: "confirmed",
    can_view: true,
  },
  {
    booking_id: 6,
    display_booking_id: "#BK 1006",
    player_name: "Lisa Anderson",
    player_id: 6,
    display_player_id: "#PL 2006",
    player_email: "lisa@email.com",
    session_id: 3,
    session_name: "Tournament Qualifier",
    field_name: "Elite Paintball Grounds",
    match_date: "2024-01-25",
    booking_date: "2024-01-20",
    booking_flow: "online",
    match_type: "Social",
    team: "team_b",
    team_display: "Rebel Alliance",
    player_count: 7,
    amount: "175.00",
    amount_display: "$175.00",
    payment_status: "pending",
    status: "open",
    can_view: true,
  },
  {
    booking_id: 7,
    display_booking_id: "#BK 1007",
    player_name: "David Lee",
    player_id: 7,
    display_player_id: "#PL 2007",
    player_email: "david@email.com",
    session_id: 4,
    session_name: "Corporate Team Building",
    field_name: "Fun Zone Arena",
    match_date: "2024-01-28",
    booking_date: "2024-01-21",
    booking_flow: "walk_in",
    match_type: "Social",
    team: "team_a",
    team_display: "Company A",
    player_count: 10,
    amount: "250.00",
    amount_display: "$250.00",
    payment_status: "paid",
    status: "confirmed",
    can_view: true,
  },
  {
    booking_id: 8,
    display_booking_id: "#BK 1008",
    player_name: "Amanda Garcia",
    player_id: 8,
    display_player_id: "#PL 2008",
    player_email: "amanda@email.com",
    session_id: 4,
    session_name: "Corporate Team Building",
    field_name: "Fun Zone Arena",
    match_date: "2024-01-28",
    booking_date: "2024-01-22",
    booking_flow: "online",
    match_type: "Ranked",
    team: "team_b",
    team_display: "Company B",
    player_count: 9,
    amount: "225.00",
    amount_display: "$225.00",
    payment_status: "paid",
    status: "confirmed",
    can_view: true,
  },
  {
    booking_id: 9,
    display_booking_id: "#BK 1009",
    player_name: "Robert Martinez",
    player_id: 9,
    display_player_id: "#PL 2009",
    player_email: "robert@email.com",
    session_id: 5,
    session_name: "Pro League Practice",
    field_name: "Champions Arena",
    match_date: "2024-01-30",
    booking_date: "2024-01-23",
    booking_flow: "online",
    match_type: "Ranked",
    team: "team_a",
    team_display: "Pro Stars",
    player_count: 12,
    amount: "300.00",
    amount_display: "$300.00",
    payment_status: "paid",
    status: "confirmed",
    can_view: true,
  },
  {
    booking_id: 10,
    display_booking_id: "#BK 1010",
    player_name: "Jennifer Taylor",
    player_id: 10,
    display_player_id: "#PL 2010",
    player_email: "jennifer@email.com",
    session_id: 5,
    session_name: "Pro League Practice",
    field_name: "Champions Arena",
    match_date: "2024-01-30",
    booking_date: "2024-01-24",
    booking_flow: "walk_in",
    match_type: "Social",
    team: "team_b",
    team_display: "Rising Suns",
    player_count: 11,
    amount: "275.00",
    amount_display: "$275.00",
    payment_status: "pending",
    status: "open",
    can_view: true,
  },
]

/** Mock booking details for the detail sheet */
export const mockBookingDetails: BookingDetailsResponse = {
  success: true,
  message: "Booking details retrieved successfully",
  meta: {},
  data: {
    booking: {
      id: 1,
      display_booking_id: "#BK 1001",
      status: "confirmed",
      payment_status: "paid",
      payment_reference: "TXN-2024-001",
      booking_flow: "online",
      team: "team_a",
      team_display: "Alpha Squad",
      player_count: 5,
      created_at: "2024-01-15",
      paid_at: "2024-01-15",
      confirmed_at: "2024-01-15",
    },
    player: {
      id: 1,
      display_player_id: "#PL 2001",
      full_name: "John Smith",
      email: "john.smith@email.com",
      contact_number: "+1 555-0123",
      location: "New York, USA",
      profile_image: null,
    },
    session: {
      id: 1,
      session_name: "Weekend Warrior Match",
      field_name: "Tactical Arena NYC",
      match_type: "Ranked",
      session_visibility: "public",
      match_date: "2024-01-20",
      start_time: "14:00",
      end_time: "16:00",
      team_a_name: "Alpha Squad",
      team_b_name: "Bravo Team",
      entry_fee: "25.00",
      status: "open",
    },
    payment: {
      entry_fee_total: "125.00",
      package_fee: "10.00",
      commission_rate: "5%",
      commission_amount: "6.75",
      total_amount: "131.75",
      total_amount_display: "$131.75",
      currency: "USD",
      payment_method: "Credit Card",
    },
    package: {
      id: 1,
      package_name: "Standard Package",
      package_fee: "10.00",
      description: "Basic equipment rental",
      include_items: ["Mask", "Gun", "50 Paintballs"],
    },
    selected_players: [
      {
        id: 1,
        full_name: "John Smith",
        email: "john@email.com",
        profile_image: null,
      },
      {
        id: 2,
        full_name: "Sarah Johnson",
        email: "sarah@email.com",
        profile_image: null,
      },
    ],
    session_booking: {
      id: 1,
      status: "confirmed",
      paid_amount: "131.75",
      payment_status: "paid",
    },
  },
  requestId: "req-001",
}
