/**
 * earnings-mock-data.ts
 * Mock data for the Earnings feature.
 * Contains sample earnings list items and transaction details
 * for frontend demonstration without API integration.
 */

import type {
  EarningsListItem,
  TransactionDetailsResponse,
} from "@/types/DashboardTypes/EarningsTypes"

/** Mock earnings list data for the table */
export const mockEarningsListData: EarningsListItem[] = [
  {
    transaction_id: 1,
    display_transaction_id: "#TXN 5001",
    payment_reference: "REF-2024-001",
    user_name: "John Smith",
    user_id: 1,
    display_user_id: "#PL 2001",
    user_email: "john@email.com",
    plan: "Standard",
    session_id: 1,
    display_session_id: "#SS 3001",
    session_name: "Weekend Warrior",
    session_type: "ranked",
    session_type_display: "Ranked",
    amount: "125.00",
    amount_display: "$125.00",
    currency: "USD",
    date: "2024-01-20",
    date_display: "Jan 20, 2024",
    field_name: "Tactical Arena NYC",
    payment_method: "stripe",
    payment_method_display: "Stripe",
    payment_status: "paid",
    status: "completed",
    can_view: true,
  },
  {
    transaction_id: 2,
    display_transaction_id: "#TXN 5002",
    payment_reference: "REF-2024-002",
    user_name: "Sarah Johnson",
    user_id: 2,
    display_user_id: "#PL 2002",
    user_email: "sarah@email.com",
    plan: "Premium",
    session_id: 1,
    display_session_id: "#SS 3001",
    session_name: "Weekend Warrior",
    session_type: "social",
    session_type_display: "Social",
    amount: "100.00",
    amount_display: "$100.00",
    currency: "USD",
    date: "2024-01-20",
    date_display: "Jan 20, 2024",
    field_name: "Tactical Arena NYC",
    payment_method: "cash",
    payment_method_display: "Cash",
    payment_status: "paid",
    status: "completed",
    can_view: true,
  },
  {
    transaction_id: 3,
    display_transaction_id: "#TXN 5003",
    payment_reference: "REF-2024-003",
    user_name: "Mike Davis",
    user_id: 3,
    display_user_id: "#PL 2003",
    user_email: "mike@email.com",
    plan: "Standard",
    session_id: 2,
    display_session_id: "#SS 3002",
    session_name: "Night Ops Match",
    session_type: "ranked",
    session_type_display: "Ranked",
    amount: "150.00",
    amount_display: "$150.00",
    currency: "USD",
    date: "2024-01-22",
    date_display: "Jan 22, 2024",
    field_name: "Shadow Ops Center",
    payment_method: "stripe",
    payment_method_display: "Stripe",
    payment_status: "paid",
    status: "completed",
    can_view: true,
  },
  {
    transaction_id: 4,
    display_transaction_id: "#TXN 5004",
    payment_reference: "REF-2024-004",
    user_name: "Emily Brown",
    user_id: 4,
    display_user_id: "#PL 2004",
    user_email: "emily@email.com",
    plan: "Basic",
    session_id: 2,
    display_session_id: "#SS 3002",
    session_name: "Night Ops Match",
    session_type: "social",
    session_type_display: "Social",
    amount: "75.00",
    amount_display: "$75.00",
    currency: "USD",
    date: "2024-01-22",
    date_display: "Jan 22, 2024",
    field_name: "Shadow Ops Center",
    payment_method: "cash",
    payment_method_display: "Cash",
    payment_status: "pending",
    status: "pending",
    can_view: true,
  },
  {
    transaction_id: 5,
    display_transaction_id: "#TXN 5005",
    payment_reference: "REF-2024-005",
    user_name: "Chris Wilson",
    user_id: 5,
    display_user_id: "#PL 2005",
    user_email: "chris@email.com",
    plan: "Premium",
    session_id: 3,
    display_session_id: "#SS 3003",
    session_name: "Tournament Qualifier",
    session_type: "ranked",
    session_type_display: "Ranked",
    amount: "200.00",
    amount_display: "$200.00",
    currency: "USD",
    date: "2024-01-25",
    date_display: "Jan 25, 2024",
    field_name: "Elite Paintball Grounds",
    payment_method: "stripe",
    payment_method_display: "Stripe",
    payment_status: "paid",
    status: "completed",
    can_view: true,
  },
  {
    transaction_id: 6,
    display_transaction_id: "#TXN 5006",
    payment_reference: "REF-2024-006",
    user_name: "Lisa Anderson",
    user_id: 6,
    display_user_id: "#PL 2006",
    user_email: "lisa@email.com",
    plan: "Standard",
    session_id: 3,
    display_session_id: "#SS 3003",
    session_name: "Tournament Qualifier",
    session_type: "social",
    session_type_display: "Social",
    amount: "175.00",
    amount_display: "$175.00",
    currency: "USD",
    date: "2024-01-25",
    date_display: "Jan 25, 2024",
    field_name: "Elite Paintball Grounds",
    payment_method: "cash",
    payment_method_display: "Cash",
    payment_status: "paid",
    status: "completed",
    can_view: true,
  },
  {
    transaction_id: 7,
    display_transaction_id: "#TXN 5007",
    payment_reference: "REF-2024-007",
    user_name: "David Lee",
    user_id: 7,
    display_user_id: "#PL 2007",
    user_email: "david@email.com",
    plan: "Basic",
    session_id: 4,
    display_session_id: "#SS 3004",
    session_name: "Corporate Team Building",
    session_type: "social",
    session_type_display: "Social",
    amount: "250.00",
    amount_display: "$250.00",
    currency: "USD",
    date: "2024-01-28",
    date_display: "Jan 28, 2024",
    field_name: "Fun Zone Arena",
    payment_method: "stripe",
    payment_method_display: "Stripe",
    payment_status: "paid",
    status: "completed",
    can_view: true,
  },
  {
    transaction_id: 8,
    display_transaction_id: "#TXN 5008",
    payment_reference: "REF-2024-008",
    user_name: "Amanda Garcia",
    user_id: 8,
    display_user_id: "#PL 2008",
    user_email: "amanda@email.com",
    plan: "Premium",
    session_id: 4,
    display_session_id: "#SS 3004",
    session_name: "Corporate Team Building",
    session_type: "ranked",
    session_type_display: "Ranked",
    amount: "225.00",
    amount_display: "$225.00",
    currency: "USD",
    date: "2024-01-28",
    date_display: "Jan 28, 2024",
    field_name: "Fun Zone Arena",
    payment_method: "stripe",
    payment_method_display: "Stripe",
    payment_status: "paid",
    status: "completed",
    can_view: true,
  },
  {
    transaction_id: 9,
    display_transaction_id: "#TXN 5009",
    payment_reference: "REF-2024-009",
    user_name: "Robert Martinez",
    user_id: 9,
    display_user_id: "#PL 2009",
    user_email: "robert@email.com",
    plan: "Standard",
    session_id: 5,
    display_session_id: "#SS 3005",
    session_name: "Pro League Practice",
    session_type: "ranked",
    session_type_display: "Ranked",
    amount: "300.00",
    amount_display: "$300.00",
    currency: "USD",
    date: "2024-01-30",
    date_display: "Jan 30, 2024",
    field_name: "Champions Arena",
    payment_method: "cash",
    payment_method_display: "Cash",
    payment_status: "paid",
    status: "completed",
    can_view: true,
  },
  {
    transaction_id: 10,
    display_transaction_id: "#TXN 5010",
    payment_reference: "REF-2024-010",
    user_name: "Jennifer Taylor",
    user_id: 10,
    display_user_id: "#PL 2010",
    user_email: "jennifer@email.com",
    plan: "Basic",
    session_id: 5,
    display_session_id: "#SS 3005",
    session_name: "Pro League Practice",
    session_type: "social",
    session_type_display: "Social",
    amount: "275.00",
    amount_display: "$275.00",
    currency: "USD",
    date: "2024-01-30",
    date_display: "Jan 30, 2024",
    field_name: "Champions Arena",
    payment_method: "stripe",
    payment_method_display: "Stripe",
    payment_status: "paid",
    status: "completed",
    can_view: true,
  },
]

/** Mock transaction details for the detail sheet */
export const mockTransactionDetails: TransactionDetailsResponse = {
  success: true,
  message: "Transaction details retrieved successfully",
  meta: {},
  data: {
    transaction_details: {
      title: "Transaction Details",
      subtitle: "View complete transaction and payment information.",
      status: "completed",
      status_display: "Paid",
      player_info: {
        booking_id: 1,
        display_booking_id: "#BK 1001",
        session_id: 1,
        display_session_id: "#SS 3001",
        player_name: "John Smith",
        player_id: 1,
        display_player_id: "#PL 2001",
        email: "john.smith@email.com",
      },
      payment_info: {
        transaction_id: 1,
        display_transaction_id: "#TXN 5001",
        amount: "125.00",
        amount_display: "$125.00",
        platform_fee_label: "Platform Fee",
        platform_fee: "6.25",
        platform_fee_display: "$6.25",
        net_profit: "118.75",
        net_profit_display: "$118.75",
        payment_method: "stripe",
        payment_method_display: "Stripe",
        date_time: "2024-01-20T14:30:00Z",
        date_time_display: "Jan 20, 2024 at 2:30 PM",
      },
      actions: {
        cancel_button_text: "Cancel",
        download_button_text: "Download and Print",
        can_download: true,
        can_print: true,
      },
    },
  },
  requestId: "req-earn-001",
}
