import type { NotificationItem } from "@/types/DashboardTypes/NotificationTypes"

export const mockNotifications: NotificationItem[] = [
  {
    notification_id: 1,
    title: "New Booking Received",
    message: "Alex Martinez booked 'Beginner Package' for May 15, 2026 session.",
    type: "booking",
    category: "bookings",
    timestamp: "2 minutes ago",
    is_read: false,
    sender: "Alex Martinez",
  },
  {
    notification_id: 2,
    title: "Session Cancelled",
    message: "The 'Advanced Combat' session scheduled for May 12, 2026 has been cancelled by the organizer.",
    type: "warning",
    category: "sessions",
    timestamp: "15 minutes ago",
    is_read: false,
    sender: "System",
  },
  {
    notification_id: 3,
    title: "Payment Received",
    message: "Payment of €45.00 received from Player #1284 for 'Tournament Package'.",
    type: "payment",
    category: "payments",
    timestamp: "1 hour ago",
    is_read: false,
    sender: "Payment Gateway",
  },
  {
    notification_id: 4,
    title: "Session Full",
    message: "'Weekend Warrior Special' session on May 18, 2026 has reached full capacity.",
    type: "success",
    category: "sessions",
    timestamp: "2 hours ago",
    is_read: true,
    sender: "System",
  },
  {
    notification_id: 5,
    title: "New Player Registration",
    message: "A new player 'Sarah Johnson' has registered and booked a session at your arena.",
    type: "info",
    category: "system",
    timestamp: "3 hours ago",
    is_read: true,
    sender: "Sarah Johnson",
  },
  {
    notification_id: 6,
    title: "Subscription Expiring",
    message: "Your Gold subscription will expire in 5 days. Renew to keep premium features.",
    type: "error",
    category: "system",
    timestamp: "5 hours ago",
    is_read: false,
    sender: "TACPLAY",
  },
  {
    notification_id: 7,
    title: "Booking Confirmed",
    message: "Player 'Mike Davis' booking for 'Social Match' has been confirmed.",
    type: "booking",
    category: "bookings",
    timestamp: "6 hours ago",
    is_read: true,
    sender: "Mike Davis",
  },
  {
    notification_id: 8,
    title: "Staff Check-In",
    message: "Staff member 'John Smith' checked in for today's 'Ranked Tournament' session.",
    type: "info",
    category: "sessions",
    timestamp: "8 hours ago",
    is_read: true,
    sender: "John Smith",
  },
  {
    notification_id: 9,
    title: "Refund Processed",
    message: "Refund of €25.00 has been processed for cancelled booking #BK-2847.",
    type: "payment",
    category: "payments",
    timestamp: "12 hours ago",
    is_read: true,
    sender: "Payment Gateway",
  },
  {
    notification_id: 10,
    title: "Review Received",
    message: "Player 'Emma Wilson' left a 5-star review for your 'Premium Paintball' session.",
    type: "success",
    category: "system",
    timestamp: "1 day ago",
    is_read: true,
    sender: "Emma Wilson",
  },
  {
    notification_id: 11,
    title: "New Booking Received",
    message: "Carlos Garcia booked 'Private Group Package' for a corporate event on May 20, 2026.",
    type: "booking",
    category: "bookings",
    timestamp: "1 day ago",
    is_read: true,
    sender: "Carlos Garcia",
  },
  {
    notification_id: 12,
    title: "Low Inventory Alert",
    message: "Paintball inventory is running low. Current stock: 500 rounds. Reorder recommended.",
    type: "warning",
    category: "system",
    timestamp: "2 days ago",
    is_read: true,
    sender: "System",
  },
]
