/**
 * sessions-mock-data.ts
 * Mock data for the Sessions feature.
 * Contains sample sessions list items, session details, session info,
 * and player details for frontend demonstration without API integration.
 */

import type {
  SessionsListItem,
  SessionDetailsResponse,
  SessionInfoResponse,
  SessionPlayerInfoResponse,
} from "@/types/DashboardTypes/SessionTypes"

/** Mock sessions list data for the table */
export const mockSessionsListData: SessionsListItem[] = [
  {
    id: 1,
    session_id: "#SS 3001",
    session_name: "Beginner Walk-On",
    date: "Jan 26, 2026",
    time: "10:00AM - 12:00AM",
    date_time: "26 Jan 2026\n10:00AM - 12:00AM",
    match_type: "social",
    match_type_display: "Social",
    assign_staff: "James Robin",
    player: "8/8",
    booked: "2/8",
    price: 40,
    status: "open",
    status_display: "Open",
    disabled: false,
  },
  {
    id: 2,
    session_id: "#SS 3002",
    session_name: "Beginner Walk-On",
    date: "Jan 26, 2026",
    time: "10:00AM - 12:00AM",
    date_time: "26 Jan 2026\n10:00AM - 12:00AM",
    match_type: "social",
    match_type_display: "Social",
    assign_staff: "James Robin",
    player: "8/8",
    booked: "2/8",
    price: 40,
    status: "ongoing",
    status_display: "Ongoing",
    disabled: false,
  },
  {
    id: 3,
    session_id: "#SS 3003",
    session_name: "Beginner Walk-On",
    date: "Jan 26, 2026",
    time: "10:00AM - 12:00AM",
    date_time: "26 Jan 2026\n10:00AM - 12:00AM",
    match_type: "social",
    match_type_display: "Social",
    assign_staff: "James Robin",
    player: "8/8",
    booked: "2/8",
    price: 40,
    status: "open",
    status_display: "Open",
    disabled: false,
  },
  {
    id: 4,
    session_id: "#SS 3004",
    session_name: "Beginner Walk-On",
    date: "Jan 26, 2026",
    time: "10:00AM - 12:00AM",
    date_time: "26 Jan 2026\n10:00AM - 12:00AM",
    match_type: "social",
    match_type_display: "Social",
    assign_staff: "James Robin",
    player: "8/8",
    booked: "2/8",
    price: 40,
    status: "full",
    status_display: "Full",
    disabled: false,
  },
  {
    id: 5,
    session_id: "#SS 3005",
    session_name: "Beginner Walk-On",
    date: "Jan 26, 2026",
    time: "10:00AM - 12:00AM",
    date_time: "26 Jan 2026\n10:00AM - 12:00AM",
    match_type: "social",
    match_type_display: "Social",
    assign_staff: "James Robin",
    player: "8/8",
    booked: "2/8",
    price: 40,
    status: "completed",
    status_display: "Complete",
    disabled: false,
  },
  {
    id: 6,
    session_id: "#SS 3006",
    session_name: "Beginner Walk-On",
    date: "Jan 26, 2026",
    time: "10:00AM - 12:00AM",
    date_time: "26 Jan 2026\n10:00AM - 12:00AM",
    match_type: "social",
    match_type_display: "Social",
    assign_staff: "James Robin",
    player: "8/8",
    booked: "2/8",
    price: 40,
    status: "full",
    status_display: "Full",
    disabled: false,
  },
  {
    id: 7,
    session_id: "#SS 3007",
    session_name: "Beginner Walk-On",
    date: "Jan 26, 2026",
    time: "10:00AM - 12:00AM",
    date_time: "26 Jan 2026\n10:00AM - 12:00AM",
    match_type: "social",
    match_type_display: "Social",
    assign_staff: "James Robin",
    player: "8/8",
    booked: "2/8",
    price: 40,
    status: "ongoing",
    status_display: "Ongoing",
    disabled: false,
  },
  {
    id: 8,
    session_id: "#SS 3008",
    session_name: "Beginner Walk-On",
    date: "Jan 26, 2026",
    time: "10:00AM - 12:00AM",
    date_time: "26 Jan 2026\n10:00AM - 12:00AM",
    match_type: "social",
    match_type_display: "Social",
    assign_staff: "James Robin",
    player: "8/8",
    booked: "2/8",
    price: 40,
    status: "open",
    status_display: "Open",
    disabled: false,
  },
  {
    id: 9,
    session_id: "#SS 3009",
    session_name: "Beginner Walk-On",
    date: "Jan 26, 2026",
    time: "10:00AM - 12:00AM",
    date_time: "26 Jan 2026\n10:00AM - 12:00AM",
    match_type: "social",
    match_type_display: "Social",
    assign_staff: "James Robin",
    player: "8/8",
    booked: "2/8",
    price: 40,
    status: "ongoing",
    status_display: "Ongoing",
    disabled: false,
  },
  {
    id: 10,
    session_id: "#SS 3010",
    session_name: "Beginner Walk-On",
    date: "Jan 26, 2026",
    time: "10:00AM - 12:00AM",
    date_time: "26 Jan 2026\n10:00AM - 12:00AM",
    match_type: "social",
    match_type_display: "Social",
    assign_staff: "James Robin",
    player: "8/8",
    booked: "2/8",
    price: 40,
    status: "open",
    status_display: "Open",
    disabled: false,
  },
]

/** Mock session details for the details page */
export const mockSessionDetails: SessionDetailsResponse["data"] = {
  id: 1,
  session_id: "#SS 3001",
  session_name: "Speedball",
  match_type: "ranked",
  match_type_display: "Ranked",
  session_visibility: "premium",
  description: "An exciting ranked match session for experienced players.",
  match_date: "Jan 26, 2026",
  start_time: "10:00 AM",
  start_time_period: "AM",
  end_time: "12:00 PM",
  end_time_period: "PM",
  time: "50:25",
  duration: 120,
  booking_cut_off_time: 12,
  booking_cut_off_unit: "hours",
  team_a_player: 4,
  team_b_player: 4,
  session_type: "teams",
  team_a_name: "Snake Green Squad",
  team_b_name: "Red Bull Squad",
  team_a_logo: "/green-team.png",
  team_b_logo: "/red-team.png",
  entry_fee: 25,
  team_a_score: 254,
  team_b_score: 254,
  status: "ongoing",
  status_display: "Ongoing",
  owner: 1,
  top_summary: {
    team_a: { name: "Snake Green Squad", logo: "/green-team.png", score: 254 },
    team_b: { name: "Red Bull Squad", logo: "/red-team.png", score: 254 },
    team_full: {
      booked_display: "8/8",
      team_a_booked: 4,
      team_b_booked: 4,
      team_a_capacity: 4,
      team_b_capacity: 4,
      team_a_display: "8/8",
      team_b_display: "8/8",
    },
  },
  team_a_players: [
    {
      player_id: 1, booking_id: 101, name: "Elon Rektler",
      image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop&crop=face",
      wins: { count: 95, points: 450 }, losses: { count: 25, points: 150 }, draws: { count: 0, points: 0 },
      rank: 195, score: 254, score_display: "+20", email: "elon@email.com", season_points: 1200,
      checked_in: true, checked_in_at: "2026-01-26T09:55:00Z", result: "win", result_display: "Win", awarded_score: 20,
    },
    {
      player_id: 2, booking_id: 102, name: "Elon Rektler",
      image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
      wins: { count: 95, points: 300 }, losses: { count: 25, points: 200 }, draws: { count: 0, points: 0 },
      rank: 254, score: 254, score_display: "00", email: "elon2@email.com", season_points: 950,
      checked_in: true, checked_in_at: "2026-01-26T09:58:00Z", result: "win", result_display: "Win", awarded_score: 0,
    },
    {
      player_id: 3, booking_id: 103, name: "Elon Rektler",
      image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face",
      wins: { count: 95, points: 280 }, losses: { count: 25, points: 180 }, draws: { count: 1, points: 50 },
      rank: 195, score: 254, score_display: "+20", email: "elon3@email.com", season_points: 880,
      checked_in: true, checked_in_at: "2026-01-26T10:00:00Z", result: "loss", result_display: "Loss", awarded_score: 20,
    },
    {
      player_id: 4, booking_id: 104, name: "Elon Rektler",
      image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face",
      wins: { count: 95, points: 150 }, losses: { count: 25, points: 100 }, draws: { count: 0, points: 0 },
      rank: 254, score: 254, score_display: "-", email: "elon4@email.com", season_points: 720,
      checked_in: true, checked_in_at: "2026-01-26T10:02:00Z", result: "loss", result_display: "Loss", awarded_score: 0,
    },
  ],
  team_b_players: [
    {
      player_id: 5, booking_id: 201, name: "Elon Rektler",
      image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&h=200&fit=crop&crop=face",
      wins: { count: 95, points: 320 }, losses: { count: 25, points: 200 }, draws: { count: 0, points: 0 },
      rank: 195, score: 254, score_display: "+20", email: "elon5@email.com", season_points: 1100,
      checked_in: true, checked_in_at: "2026-01-26T09:50:00Z", result: "win", result_display: "Win", awarded_score: 20,
    },
    {
      player_id: 6, booking_id: 202, name: "Elon Rektler",
      image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop&crop=face",
      wins: { count: 95, points: 290 }, losses: { count: 25, points: 180 }, draws: { count: 0, points: 0 },
      rank: 195, score: 254, score_display: "00", email: "elon6@email.com", season_points: 920,
      checked_in: true, checked_in_at: "2026-01-26T09:52:00Z", result: "win", result_display: "Win", awarded_score: 0,
    },
    {
      player_id: 7, booking_id: 203, name: "Elon Rektler",
      image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
      wins: { count: 95, points: 180 }, losses: { count: 25, points: 120 }, draws: { count: 0, points: 0 },
      rank: 195, score: 254, score_display: "-", email: "elon7@email.com", season_points: 780,
      checked_in: true, checked_in_at: "2026-01-26T09:55:00Z", result: "loss", result_display: "Loss", awarded_score: 0,
    },
    {
      player_id: 8, booking_id: 204, name: "Elon Rektler",
      image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face",
      wins: { count: 95, points: 160 }, losses: { count: 25, points: 100 }, draws: { count: 0, points: 0 },
      rank: 195, score: 254, score_display: "00", email: "elon8@email.com", season_points: 680,
      checked_in: true, checked_in_at: "2026-01-26T09:58:00Z", result: "loss", result_display: "Loss", awarded_score: 0,
    },
  ],
}

/** Mock session info for the info sheet */
export const mockSessionInfo: SessionInfoResponse = {
  success: true,
  message: "Session info retrieved successfully",
  meta: {},
  data: {
    status: "open",
    status_display: "Open",
    field_info: {
      field_id: "#FL 1001",
      field_name: "Tactical Arena NYC",
      location: "New York, USA",
      contact_number: "+1 555-0123",
    },
    session_info: {
      session_id: "#SS 3001",
      session_name: "Beginner Walk-On",
      match_type: "social",
      match_type_display: "Social",
      session_date: "Jan 26, 2026",
      time: "10:00AM - 12:00AM",
      session_type: "Team",
      team: "Snake Green Squad vs Red Bull Squad",
      player_per_team: "4",
      packages: "Standard Package",
    },
    team_info: {
      team_a_name: "Snake Green Squad",
      team_a_score: 0,
      team_b_name: "Red Bull Squad",
      team_b_score: 0,
      champion: "N/A",
      team_a_booked: 4,
      team_b_booked: 4,
      team_a_capacity: 4,
      team_b_capacity: 4,
    },
    actions: {
      can_start_match: true,
      can_submit_final_result: false,
      can_cancel_match: true,
      primary_button: "Match Start",
    },
  },
  requestId: "req-session-info-001",
}

/** Mock player details for the player details sheet */
export const mockPlayerDetails: SessionPlayerInfoResponse = {
  success: true,
  message: "Player details retrieved successfully",
  meta: {},
  data: {
    session_id: 1,
    booking_id: 101,
    session_type: "ranked",
    session_type_display: "Ranked",
    session_status: "open",
    session_status_display: "Open",
    player_info: {
      team_name: "Snake Green Squad",
      player_id: "#PL 2001",
      player_name: "Elon Rektler",
      email: "elon.rektler@email.com",
      contact_number: "+1 555-0123",
    },
    booking_info: {
      booking_id: "#BK 1001",
      transaction_id: "#TXN 5001",
      amount: "$125.00",
      platform_fee: "$6.25",
      net_profit: "$118.75",
      payment_method: "Stripe",
      date_time: "Jan 26, 2026 at 10:30 AM",
      payment_status: "Paid",
    },
    score_management: {
      checked_in: false,
      checked_in_at: null,
      result: "pending",
      result_display: "Pending",
      awarded_score: 0,
      show_result_selector: true,
      show_check_in_button: true,
      show_submit_button: true,
    },
  },
  requestId: "req-player-info-001",
}
