/**
 * sessions-mock-data.ts
 * Mock data for the Sessions feature.
 * Contains sample sessions list items, session details, session info,
 * and player details for frontend demonstration without API integration.
 */

import type {
  SessionsListItem,
  SessionDetailsResponse,
  SessionInfoResponse,
  SessionPlayerInfoResponse,
} from "@/types/DashboardTypes/SessionTypes"

/** Mock sessions list data for the table */
export const mockSessionsListData: SessionsListItem[] = [
  {
    id: 1,
    session_id: "#SS 3001",
    session_name: "Weekend Warrior",
    date: "Jan 20, 2024",
    time: "2:00 PM - 4:00 PM",
    match_type: "ranked",
    match_type_display: "Ranked",
    player: "10/10",
    booked: "8/10",
    status: "open",
    status_display: "Open",
  },
  {
    id: 2,
    session_id: "#SS 3002",
    session_name: "Night Ops Match",
    date: "Jan 22, 2024",
    time: "8:00 PM - 10:00 PM",
    match_type: "social",
    match_type_display: "Social",
    player: "12/12",
    booked: "10/12",
    status: "ongoing",
    status_display: "Ongoing",
  },
  {
    id: 3,
    session_id: "#SS 3003",
    session_name: "Tournament Qualifier",
    date: "Jan 25, 2024",
    time: "10:00 AM - 1:00 PM",
    match_type: "ranked",
    match_type_display: "Ranked",
    player: "16/16",
    booked: "16/16",
    status: "completed",
    status_display: "Completed",
  },
  {
    id: 4,
    session_id: "#SS 3004",
    session_name: "Corporate Team Building",
    date: "Jan 28, 2024",
    time: "9:00 AM - 12:00 PM",
    match_type: "social",
    match_type_display: "Social",
    player: "20/20",
    booked: "18/20",
    status: "open",
    status_display: "Open",
  },
  {
    id: 5,
    session_id: "#SS 3005",
    session_name: "Pro League Practice",
    date: "Jan 30, 2024",
    time: "3:00 PM - 5:00 PM",
    match_type: "ranked",
    match_type_display: "Ranked",
    player: "8/8",
    booked: "8/8",
    status: "completed",
    status_display: "Completed",
  },
  {
    id: 6,
    session_id: "#SS 3006",
    session_name: "Beginner Training",
    date: "Feb 1, 2024",
    time: "11:00 AM - 1:00 PM",
    match_type: "social",
    match_type_display: "Social",
    player: "6/6",
    booked: "4/6",
    status: "open",
    status_display: "Open",
  },
  {
    id: 7,
    session_id: "#SS 3007",
    session_name: "Elite Championship",
    date: "Feb 3, 2024",
    time: "6:00 PM - 9:00 PM",
    match_type: "ranked",
    match_type_display: "Ranked",
    player: "24/24",
    booked: "22/24",
    status: "cancelled",
    status_display: "Cancelled",
  },
  {
    id: 8,
    session_id: "#SS 3008",
    session_name: "Casual Paintball",
    date: "Feb 5, 2024",
    time: "1:00 PM - 3:00 PM",
    match_type: "social",
    match_type_display: "Social",
    player: "8/8",
    booked: "6/8",
    status: "open",
    status_display: "Open",
  },
  {
    id: 9,
    session_id: "#SS 3009",
    session_name: "Ranked Showdown",
    date: "Feb 7, 2024",
    time: "4:00 PM - 6:00 PM",
    match_type: "ranked",
    match_type_display: "Ranked",
    player: "10/10",
    booked: "10/10",
    status: "ongoing",
    status_display: "Ongoing",
  },
  {
    id: 10,
    session_id: "#SS 3010",
    session_name: "Community Fun Day",
    date: "Feb 9, 2024",
    time: "10:00 AM - 4:00 PM",
    match_type: "social",
    match_type_display: "Social",
    player: "30/30",
    booked: "25/30",
    status: "open",
    status_display: "Open",
  },
]

/** Mock session details for the details page */
export const mockSessionDetails: SessionDetailsResponse["data"] = {
  id: 1,
  session_id: "#SS 3001",
  session_name: "Weekend Warrior",
  match_type: "ranked",
  match_type_display: "Ranked",
  session_visibility: "premium",
  description: "An exciting ranked match session for experienced players.",
  match_date: "Jan 20, 2024",
  start_time: "2:00 PM",
  start_time_period: "PM",
  end_time: "4:00 PM",
  end_time_period: "PM",
  time: "2:00 PM - 4:00 PM",
  duration: 120,
  booking_cut_off_time: 12,
  booking_cut_off_unit: "hours",
  team_a_player: 5,
  team_b_player: 5,
  session_type: "teams",
  team_a_name: "Alpha Squad",
  team_b_name: "Bravo Team",
  team_a_logo: null,
  team_b_logo: null,
  entry_fee: 25,
  team_a_score: 3,
  team_b_score: 2,
  status: "completed",
  status_display: "Completed",
  owner: 1,
  top_summary: {
    team_a: { name: "Alpha Squad", logo: null, score: 3 },
    team_b: { name: "Bravo Team", logo: null, score: 2 },
    team_full: {
      booked_display: "8/10",
      team_a_booked: 4,
      team_b_booked: 4,
      team_a_capacity: 5,
      team_b_capacity: 5,
      team_a_display: "4/5",
      team_b_display: "4/5",
    },
  },
  team_a_players: [
    {
      player_id: 1, booking_id: 101, name: "John Smith", image: null,
      wins: { count: 3, points: 450 }, losses: { count: 1, points: 150 }, draws: { count: 0, points: 0 },
      rank: 1, score: 450, score_display: "450 pts", email: "john@email.com", season_points: 1200,
      checked_in: true, checked_in_at: "2024-01-20T13:55:00Z", result: "win", result_display: "Win", awarded_score: 450,
    },
    {
      player_id: 2, booking_id: 102, name: "Mike Davis", image: null,
      wins: { count: 2, points: 300 }, losses: { count: 2, points: 200 }, draws: { count: 0, points: 0 },
      rank: 2, score: 300, score_display: "300 pts", email: "mike@email.com", season_points: 950,
      checked_in: true, checked_in_at: "2024-01-20T13:58:00Z", result: "win", result_display: "Win", awarded_score: 300,
    },
    {
      player_id: 3, booking_id: 103, name: "Chris Wilson", image: null,
      wins: { count: 2, points: 280 }, losses: { count: 2, points: 180 }, draws: { count: 1, points: 50 },
      rank: 3, score: 280, score_display: "280 pts", email: "chris@email.com", season_points: 880,
      checked_in: true, checked_in_at: "2024-01-20T14:00:00Z", result: "loss", result_display: "Loss", awarded_score: 280,
    },
    {
      player_id: 4, booking_id: 104, name: "David Lee", image: null,
      wins: { count: 1, points: 150 }, losses: { count: 3, points: 100 }, draws: { count: 0, points: 0 },
      rank: 4, score: 150, score_display: "150 pts", email: "david@email.com", season_points: 720,
      checked_in: true, checked_in_at: "2024-01-20T14:02:00Z", result: "loss", result_display: "Loss", awarded_score: 150,
    },
  ],
  team_b_players: [
    {
      player_id: 5, booking_id: 201, name: "Sarah Johnson", image: null,
      wins: { count: 2, points: 320 }, losses: { count: 2, points: 200 }, draws: { count: 0, points: 0 },
      rank: 1, score: 320, score_display: "320 pts", email: "sarah@email.com", season_points: 1100,
      checked_in: true, checked_in_at: "2024-01-20T13:50:00Z", result: "win", result_display: "Win", awarded_score: 320,
    },
    {
      player_id: 6, booking_id: 202, name: "Emily Brown", image: null,
      wins: { count: 2, points: 290 }, losses: { count: 2, points: 180 }, draws: { count: 0, points: 0 },
      rank: 2, score: 290, score_display: "290 pts", email: "emily@email.com", season_points: 920,
      checked_in: true, checked_in_at: "2024-01-20T13:52:00Z", result: "win", result_display: "Win", awarded_score: 290,
    },
    {
      player_id: 7, booking_id: 203, name: "Lisa Anderson", image: null,
      wins: { count: 1, points: 180 }, losses: { count: 3, points: 120 }, draws: { count: 0, points: 0 },
      rank: 3, score: 180, score_display: "180 pts", email: "lisa@email.com", season_points: 780,
      checked_in: true, checked_in_at: "2024-01-20T13:55:00Z", result: "loss", result_display: "Loss", awarded_score: 180,
    },
    {
      player_id: 8, booking_id: 204, name: "Amanda Garcia", image: null,
      wins: { count: 1, points: 160 }, losses: { count: 3, points: 100 }, draws: { count: 0, points: 0 },
      rank: 4, score: 160, score_display: "160 pts", email: "amanda@email.com", season_points: 680,
      checked_in: true, checked_in_at: "2024-01-20T13:58:00Z", result: "loss", result_display: "Loss", awarded_score: 160,
    },
  ],
}

/** Mock session info for the info sheet */
export const mockSessionInfo: SessionInfoResponse = {
  success: true,
  message: "Session info retrieved successfully",
  meta: {},
  data: {
    status: "open",
    status_display: "Open",
    field_info: {
      field_id: "#FL 1001",
      field_name: "Tactical Arena NYC",
      location: "New York, USA",
      contact_number: "+1 555-0123",
    },
    session_info: {
      session_id: "#SS 3001",
      session_name: "Weekend Warrior",
      match_type: "ranked",
      match_type_display: "Ranked",
      session_date: "Jan 20, 2024",
      time: "2:00 PM - 4:00 PM",
      session_type: "Team",
      team: "Alpha Squad vs Bravo Team",
      player_per_team: "5",
      packages: "Standard Package",
    },
    team_info: {
      team_a_name: "Alpha Squad",
      team_a_score: 0,
      team_b_name: "Bravo Team",
      team_b_score: 0,
      champion: "N/A",
      team_a_booked: 4,
      team_b_booked: 4,
      team_a_capacity: 5,
      team_b_capacity: 5,
    },
    actions: {
      can_start_match: true,
      can_submit_final_result: false,
      can_cancel_match: true,
      primary_button: "Match Start",
    },
  },
  requestId: "req-session-info-001",
}

/** Mock player details for the player details sheet */
export const mockPlayerDetails: SessionPlayerInfoResponse = {
  success: true,
  message: "Player details retrieved successfully",
  meta: {},
  data: {
    session_id: 1,
    booking_id: 101,
    session_type: "ranked",
    session_type_display: "Ranked",
    session_status: "open",
    session_status_display: "Open",
    player_info: {
      team_name: "Alpha Squad",
      player_id: "#PL 2001",
      player_name: "John Smith",
      email: "john.smith@email.com",
      contact_number: "+1 555-0123",
    },
    booking_info: {
      booking_id: "#BK 1001",
      transaction_id: "#TXN 5001",
      amount: "$125.00",
      platform_fee: "$6.25",
      net_profit: "$118.75",
      payment_method: "Stripe",
      date_time: "Jan 20, 2024 at 2:30 PM",
      payment_status: "Paid",
    },
    score_management: {
      checked_in: false,
      checked_in_at: null,
      result: "pending",
      result_display: "Pending",
      awarded_score: 0,
      show_result_selector: true,
      show_check_in_button: true,
      show_submit_button: true,
    },
  },
  requestId: "req-player-info-001",
}
