import type {
  SubscriptionPlan,
  CurrentSubscription,
  BillingHistoryRecord,
  PaymentMethodCard,
} from "@/types/DashboardTypes/SubscriptionTypes"

export const mockSubscriptionPlans: SubscriptionPlan[] = [
  {
    id: "1",
    name: "Bronze Plan",
    code: "field_bronze_monthly",
    price: 34.99,
    annualPrice: 279.99,
    currency: "€",
    billing_cycle: "month",
    description:
      "Essential booking, visibility and check-in tools for independent paintball fields.",
    logo: "/bronze.png",
    is_popular: false,
    features: [
      "Create and manage a field profile.",
      "Add opening hours.",
      "Add game sessions.",
      "Add basic prices and packages",
      "View Bookings.",
      "Scan player QR codes.",
    ],
  },
  {
    id: "2",
    name: "Silver Plan",
    code: "field_silver_monthly",
    price: 34.99,
    annualPrice: 279.99,
    currency: "€",
    billing_cycle: "month",
    description:
      "Growth tools for fields that want more bookings, better attendance and smarter marketing.",
    logo: "/silver.png",
    is_popular: true,
    features: [
      "Advanced field profile visibility.",
      "Enhanced analytics.",
      "AI marketing suggestions.",
      "Discount code creation.",
      "Voucher creation.",
      "Staff scanner access.",
      "Bulk session creation using a calendar.",
    ],
  },
  {
    id: "3",
    name: "Gold Plan",
    code: "field_gold_monthly",
    price: 34.99,
    annualPrice: 279.99,
    currency: "€",
    billing_cycle: "month",
    description:
      "Premium growth, analytics and automation for serious paintball field operators.",
    logo: "/gold.png",
    is_popular: false,
    features: [
      "Everything in Silver",
      "Unlimited session creation",
      "Full earnings tracking",
      "Detailed performance insights",
      "Custom field branding",
      "Coming Soon & blend Out",
    ],
  },
]

export const mockCurrentSubscription: CurrentSubscription = {
  plan_name: "Gold Plan",
  plan_code: "field_gold_monthly",
  price: 279.99,
  currency: "€",
  billing_cycle: "month",
  next_billing_date: "June 16, 2026",
  status: "active",
}

export const mockBillingHistory: BillingHistoryRecord[] = [
  {
    id: "1",
    date: "May 16, 2026",
    description: "Gold Plan - Monthly",
    amount: "€277.99",
    currency: "€",
    status: "Paid",
    invoice_id: "INV -2023-006",
  },
  {
    id: "2",
    date: "May 16, 2026",
    description: "Gold Plan - Monthly",
    amount: "€277.99",
    currency: "€",
    status: "Paid",
    invoice_id: "INV -2023-006",
  },
  {
    id: "3",
    date: "May 16, 2026",
    description: "Gold Plan - Monthly",
    amount: "€277.99",
    currency: "€",
    status: "Paid",
    invoice_id: "INV -2023-006",
  },
  {
    id: "4",
    date: "May 16, 2026",
    description: "Gold Plan - Monthly",
    amount: "€277.99",
    currency: "€",
    status: "Paid",
    invoice_id: "INV -2023-006",
  },
  {
    id: "5",
    date: "May 16, 2026",
    description: "Gold Plan - Monthly",
    amount: "€277.99",
    currency: "€",
    status: "Paid",
    invoice_id: "INV -2023-006",
  },
  {
    id: "6",
    date: "May 16, 2026",
    description: "Gold Plan - Monthly",
    amount: "€277.99",
    currency: "€",
    status: "Paid",
    invoice_id: "INV -2023-006",
  },
  {
    id: "7",
    date: "May 16, 2026",
    description: "Gold Plan - Monthly",
    amount: "€277.99",
    currency: "€",
    status: "Paid",
    invoice_id: "INV -2023-006",
  },
  {
    id: "8",
    date: "May 16, 2026",
    description: "Gold Plan - Monthly",
    amount: "€277.99",
    currency: "€",
    status: "Paid",
    invoice_id: "INV -2023-006",
  },
  {
    id: "9",
    date: "May 16, 2026",
    description: "Gold Plan - Monthly",
    amount: "€277.99",
    currency: "€",
    status: "Paid",
    invoice_id: "INV -2023-006",
  },
  {
    id: "10",
    date: "May 16, 2026",
    description: "Gold Plan - Monthly",
    amount: "€277.99",
    currency: "€",
    status: "Paid",
    invoice_id: "INV -2023-006",
  },
  {
    id: "11",
    date: "May 16, 2026",
    description: "Gold Plan - Monthly",
    amount: "€277.99",
    currency: "€",
    status: "Paid",
    invoice_id: "INV -2023-006",
  },
  {
    id: "12",
    date: "May 16, 2026",
    description: "Gold Plan - Monthly",
    amount: "€277.99",
    currency: "€",
    status: "Paid",
    invoice_id: "INV -2023-006",
  },
  {
    id: "13",
    date: "May 16, 2026",
    description: "Gold Plan - Monthly",
    amount: "€277.99",
    currency: "€",
    status: "Paid",
    invoice_id: "INV -2023-006",
  },
  {
    id: "14",
    date: "May 16, 2026",
    description: "Gold Plan - Monthly",
    amount: "€277.99",
    currency: "€",
    status: "Paid",
    invoice_id: "INV -2023-006",
  },
]

export const mockPrimaryPaymentCard: PaymentMethodCard = {
  id: "1",
  card_type: "visa",
  last_four: "4242",
  expiry_month: "04",
  expiry_year: "26",
  is_default: true,
  cardholder_name: "Carlos Martinez",
  billing_address: "Calle de la pintura 12\n28001 Madrid, Spain",
}

export const mockOtherPaymentCards: PaymentMethodCard[] = [
  {
    id: "2",
    card_type: "mastercard",
    last_four: "4242",
    expiry_month: "04",
    expiry_year: "26",
    is_default: false,
  },
  {
    id: "3",
    card_type: "amex",
    last_four: "4242",
    expiry_month: "04",
    expiry_year: "26",
    is_default: false,
  },
]
