import type { EarningTransaction } from "@/types/AdminTypes/EarningTypes"

export const mockEarningData: EarningTransaction[] = [
  {
    id: 1,
    transaction_id: "#CH 565",
    user_name: "Kathryn Murphy",
    user_email: "lline@yandex.ru",
    user_id: "#CH 565",
    type: "Field Owner",
    country: "Spain",
    country_code: "ES",
    plan: "Bronze",
    amount: 2200,
    date: "May 2, 2026",
  },
  {
    id: 2,
    transaction_id: "#CH 565",
    user_name: "Kathryn Murphy",
    user_email: "lline@yandex.ru",
    user_id: "#CH 565",
    type: "Player",
    country: "Spain",
    country_code: "ES",
    plan: "Premium",
    amount: 2200,
    date: "May 2, 2026",
  },
  {
    id: 3,
    transaction_id: "#CH 565",
    user_name: "Kathryn Murphy",
    user_email: "lline@yandex.ru",
    user_id: "#CH 565",
    type: "Marketplace",
    country: "Spain",
    country_code: "ES",
    plan: null,
    amount: 2200,
    date: "May 2, 2026",
  },
  {
    id: 4,
    transaction_id: "#CH 565",
    user_name: "Kathryn Murphy",
    user_email: "lline@yandex.ru",
    user_id: "#CH 565",
    type: "Player",
    country: "Spain",
    country_code: "ES",
    plan: "Premium",
    amount: 2200,
    date: "May 2, 2026",
  },
  {
    id: 5,
    transaction_id: "#CH 565",
    user_name: "Kathryn Murphy",
    user_email: "lline@yandex.ru",
    user_id: "#CH 565",
    type: "Field Owner",
    country: "Spain",
    country_code: "ES",
    plan: "Silver",
    amount: 2200,
    date: "May 2, 2026",
  },
  {
    id: 6,
    transaction_id: "#CH 565",
    user_name: "Kathryn Murphy",
    user_email: "lline@yandex.ru",
    user_id: "#CH 565",
    type: "Player",
    country: "Spain",
    country_code: "ES",
    plan: "Premium",
    amount: 2200,
    date: "May 2, 2026",
  },
  {
    id: 7,
    transaction_id: "#CH 565",
    user_name: "Kathryn Murphy",
    user_email: "lline@yandex.ru",
    user_id: "#CH 565",
    type: "Marketplace",
    country: "Spain",
    country_code: "ES",
    plan: null,
    amount: 2200,
    date: "May 2, 2026",
  },
  {
    id: 8,
    transaction_id: "#CH 565",
    user_name: "Kathryn Murphy",
    user_email: "lline@yandex.ru",
    user_id: "#CH 565",
    type: "Field Owner",
    country: "Spain",
    country_code: "ES",
    plan: "Gold",
    amount: 2200,
    date: "May 2, 2026",
  },
  {
    id: 9,
    transaction_id: "#CH 565",
    user_name: "Kathryn Murphy",
    user_email: "lline@yandex.ru",
    user_id: "#CH 565",
    type: "Player",
    country: "Spain",
    country_code: "ES",
    plan: "Premium",
    amount: 2200,
    date: "May 2, 2026",
  },
  {
    id: 10,
    transaction_id: "#CH 565",
    user_name: "Kathryn Murphy",
    user_email: "lline@yandex.ru",
    user_id: "#CH 565",
    type: "Field Owner",
    country: "Spain",
    country_code: "ES",
    plan: "Bronze",
    amount: 2200,
    date: "May 2, 2026",
  },
  {
    id: 11,
    transaction_id: "#CH 565",
    user_name: "Kathryn Murphy",
    user_email: "lline@yandex.ru",
    user_id: "#CH 565",
    type: "Marketplace",
    country: "Spain",
    country_code: "ES",
    plan: null,
    amount: 2200,
    date: "May 2, 2026",
  },
  {
    id: 12,
    transaction_id: "#CH 565",
    user_name: "Kathryn Murphy",
    user_email: "lline@yandex.ru",
    user_id: "#CH 565",
    type: "Field Owner",
    country: "Spain",
    country_code: "ES",
    plan: "Gold",
    amount: 2200,
    date: "May 2, 2026",
  },
  {
    id: 13,
    transaction_id: "#CH 565",
    user_name: "Kathryn Murphy",
    user_email: "lline@yandex.ru",
    user_id: "#CH 565",
    type: "Player",
    country: "Spain",
    country_code: "ES",
    plan: "Premium",
    amount: 2200,
    date: "May 2, 2026",
  },
  {
    id: 14,
    transaction_id: "#CH 565",
    user_name: "Kathryn Murphy",
    user_email: "lline@yandex.ru",
    user_id: "#CH 565",
    type: "Field Owner",
    country: "Spain",
    country_code: "ES",
    plan: "Silver",
    amount: 2200,
    date: "May 2, 2026",
  },
  {
    id: 15,
    transaction_id: "#CH 565",
    user_name: "Kathryn Murphy",
    user_email: "lline@yandex.ru",
    user_id: "#CH 565",
    type: "Player",
    country: "Spain",
    country_code: "ES",
    plan: "Premium",
    amount: 2200,
    date: "May 2, 2026",
  },
  {
    id: 16,
    transaction_id: "#CH 565",
    user_name: "Kathryn Murphy",
    user_email: "lline@yandex.ru",
    user_id: "#CH 565",
    type: "Marketplace",
    country: "Spain",
    country_code: "ES",
    plan: null,
    amount: 2200,
    date: "May 2, 2026",
  },
  {
    id: 17,
    transaction_id: "#CH 565",
    user_name: "Kathryn Murphy",
    user_email: "lline@yandex.ru",
    user_id: "#CH 565",
    type: "Field Owner",
    country: "Spain",
    country_code: "ES",
    plan: "Gold",
    amount: 2200,
    date: "May 2, 2026",
  },
  {
    id: 18,
    transaction_id: "#CH 565",
    user_name: "Kathryn Murphy",
    user_email: "lline@yandex.ru",
    user_id: "#CH 565",
    type: "Player",
    country: "Spain",
    country_code: "ES",
    plan: "Premium",
    amount: 2200,
    date: "May 2, 2026",
  },
  {
    id: 19,
    transaction_id: "#CH 565",
    user_name: "Kathryn Murphy",
    user_email: "lline@yandex.ru",
    user_id: "#CH 565",
    type: "Field Owner",
    country: "Spain",
    country_code: "ES",
    plan: "Bronze",
    amount: 2200,
    date: "May 2, 2026",
  },
  {
    id: 20,
    transaction_id: "#CH 565",
    user_name: "Kathryn Murphy",
    user_email: "lline@yandex.ru",
    user_id: "#CH 565",
    type: "Player",
    country: "Spain",
    country_code: "ES",
    plan: "Premium",
    amount: 2200,
    date: "May 2, 2026",
  },
]
