import type {
  Field,
  Session,
  SessionDetail,
} from "@/types/AdminTypes/FieldManagementTypes"

export const mockFieldData: Field[] = [
  {
    id: 1,
    fieldName: "Field name",
    fieldId: "FLD-09324",
    description: "Perfect for first-time players",
    ownerName: "Kathryn Murphy",
    ownerEmail: "lline@yandex.ru",
    plan: "Gold",
    countryCode: "ES",
    createdDate: "May 2, 2026",
    createdTime: "10:00 AM",
    booking: 86,
    bookingChange: 18,
    revenue: "\u20AC2,200",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=400&h=300&fit=crop",
    location: "Madrid, Spain",
    rating: 4.8,
    totalBookings: 1230,
    totalRevenue: "$42,450",
    checkInRate: 98,
    contactNumber: "+26 256 2564",
    memberSince: "Apr 14, 2026",
  },
  {
    id: 2,
    fieldName: "Field name",
    fieldId: "FLD-09325",
    description: "Perfect for first-time players",
    ownerName: "Kathryn Murphy",
    ownerEmail: "lline@yandex.ru",
    plan: "Gold",
    countryCode: "ES",
    createdDate: "May 2, 2026",
    createdTime: "10:00 AM",
    booking: 86,
    bookingChange: 18,
    revenue: "\u20AC2,200",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=400&h=300&fit=crop",
    location: "Barcelona, Spain",
    rating: 4.5,
    totalBookings: 980,
    totalRevenue: "$35,200",
    checkInRate: 95,
    contactNumber: "+34 612 345 678",
    memberSince: "Mar 10, 2026",
  },
  {
    id: 3,
    fieldName: "Field name",
    fieldId: "FLD-09326",
    description: "Perfect for first-time players",
    ownerName: "Wade Warren",
    ownerEmail: "zitka@mail.ru",
    plan: "Sliver",
    countryCode: "ES",
    createdDate: "May 2, 2026",
    createdTime: "10:00 AM",
    booking: 86,
    bookingChange: 18,
    revenue: "\u20AC2,200",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=400&h=300&fit=crop",
    location: "Valencia, Spain",
    rating: 4.2,
    totalBookings: 750,
    totalRevenue: "$28,100",
    checkInRate: 92,
    contactNumber: "+34 698 765 432",
    memberSince: "Feb 1, 2026",
  },
  {
    id: 4,
    fieldName: "Field name",
    fieldId: "FLD-09327",
    description: "Perfect for first-time players",
    ownerName: "Wade Warren",
    ownerEmail: "zitka@mail.ru",
    plan: "Sliver",
    countryCode: "ES",
    createdDate: "May 2, 2026",
    createdTime: "10:00 AM",
    booking: 86,
    bookingChange: 18,
    revenue: "\u20AC2,200",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=400&h=300&fit=crop",
    location: "Seville, Spain",
    rating: 4.0,
    totalBookings: 620,
    totalRevenue: "$22,500",
    checkInRate: 88,
    contactNumber: "+34 611 222 333",
    memberSince: "Jan 20, 2026",
  },
  {
    id: 5,
    fieldName: "Field name",
    fieldId: "FLD-09328",
    description: "Perfect for first-time players",
    ownerName: "Darlene Robertson",
    ownerEmail: "xterris@gmail.com",
    plan: "Bronze",
    countryCode: "ES",
    createdDate: "May 2, 2026",
    createdTime: "10:00 AM",
    booking: 86,
    bookingChange: 18,
    revenue: "\u20AC2,200",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=400&h=300&fit=crop",
    location: "Bilbao, Spain",
    rating: 3.9,
    totalBookings: 480,
    totalRevenue: "$18,300",
    checkInRate: 85,
    contactNumber: "+34 644 555 666",
    memberSince: "Mar 1, 2026",
  },
  {
    id: 6,
    fieldName: "Field name",
    fieldId: "FLD-09329",
    description: "Perfect for first-time players",
    ownerName: "Darlene Robertson",
    ownerEmail: "xterris@gmail.com",
    plan: "Bronze",
    countryCode: "ES",
    createdDate: "May 2, 2026",
    createdTime: "10:00 AM",
    booking: 86,
    bookingChange: 18,
    revenue: "\u20AC2,200",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=400&h=300&fit=crop",
    location: "Malaga, Spain",
    rating: 4.1,
    totalBookings: 550,
    totalRevenue: "$19,800",
    checkInRate: 90,
    contactNumber: "+34 677 888 999",
    memberSince: "Feb 15, 2026",
  },
  {
    id: 7,
    fieldName: "Field name",
    fieldId: "FLD-09330",
    description: "Perfect for first-time players",
    ownerName: "Marvin McKinney",
    ownerEmail: "miyokoto@mail.ru",
    plan: "Gold",
    countryCode: "FR",
    createdDate: "May 2, 2026",
    createdTime: "10:00 AM",
    booking: 86,
    bookingChange: 18,
    revenue: "\u20AC2,200",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=400&h=300&fit=crop",
    location: "Paris, France",
    rating: 4.7,
    totalBookings: 1100,
    totalRevenue: "$39,500",
    checkInRate: 97,
    contactNumber: "+33 1 23 45 67 89",
    memberSince: "Jan 5, 2026",
  },
  {
    id: 8,
    fieldName: "Field name",
    fieldId: "FLD-09331",
    description: "Perfect for first-time players",
    ownerName: "Marvin McKinney",
    ownerEmail: "miyokoto@mail.ru",
    plan: "Gold",
    countryCode: "FR",
    createdDate: "May 2, 2026",
    createdTime: "10:00 AM",
    booking: 86,
    bookingChange: 18,
    revenue: "\u20AC2,200",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=400&h=300&fit=crop",
    location: "Lyon, France",
    rating: 4.4,
    totalBookings: 890,
    totalRevenue: "$32,100",
    checkInRate: 93,
    contactNumber: "+33 6 12 34 56 78",
    memberSince: "Mar 15, 2026",
  },
  {
    id: 9,
    fieldName: "Field name",
    fieldId: "FLD-09332",
    description: "Perfect for first-time players",
    ownerName: "Arlene McCoy",
    ownerEmail: "quasiah@gmail.com",
    plan: "Bronze",
    countryCode: "US",
    createdDate: "May 2, 2026",
    createdTime: "10:00 AM",
    booking: 86,
    bookingChange: 18,
    revenue: "\u20AC2,200",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=400&h=300&fit=crop",
    location: "New York, US",
    rating: 4.3,
    totalBookings: 720,
    totalRevenue: "$26,400",
    checkInRate: 91,
    contactNumber: "+1 555 123 4567",
    memberSince: "Apr 5, 2026",
  },
  {
    id: 10,
    fieldName: "Field name",
    fieldId: "FLD-09333",
    description: "Perfect for first-time players",
    ownerName: "Arlene McCoy",
    ownerEmail: "quasiah@gmail.com",
    plan: "Bronze",
    countryCode: "US",
    createdDate: "May 2, 2026",
    createdTime: "10:00 AM",
    booking: 86,
    bookingChange: 18,
    revenue: "\u20AC2,200",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=400&h=300&fit=crop",
    location: "Los Angeles, US",
    rating: 4.6,
    totalBookings: 1050,
    totalRevenue: "$38,200",
    checkInRate: 96,
    contactNumber: "+1 555 987 6543",
    memberSince: "Jan 20, 2026",
  },
]

export const mockSessionData: Session[] = [
  {
    id: 1,
    sessionName: "Beginner Walk-On",
    date: "26 Jan 2026",
    time: "10:00AM - 12:00AM",
    assignStaff: "James Robin",
    matchType: "Social",
    matchTypeColor: "text-emerald-400",
    player: "8/8",
    booked: "2/8",
    price: "$40",
    status: "Failed",
  },
  {
    id: 2,
    sessionName: "Beginner Walk-On",
    date: "26 Jan 2026",
    time: "10:00AM - 12:00AM",
    assignStaff: "James Robin",
    matchType: "Social",
    matchTypeColor: "text-emerald-400",
    player: "8/8",
    booked: "2/8",
    price: "$40",
    status: "Failed",
  },
  {
    id: 3,
    sessionName: "Beginner Walk-On",
    date: "26 Jan 2026",
    time: "10:00AM - 12:00AM",
    assignStaff: "James Robin",
    matchType: "Social",
    matchTypeColor: "text-emerald-400",
    player: "8/8",
    booked: "2/8",
    price: "$40",
    status: "Booking",
  },
  {
    id: 4,
    sessionName: "Beginner Walk-On",
    date: "26 Jan 2026",
    time: "10:00AM - 12:00AM",
    assignStaff: "James Robin",
    matchType: "Social",
    matchTypeColor: "text-emerald-400",
    player: "8/8",
    booked: "2/8",
    price: "$40",
    status: "Full",
  },
  {
    id: 5,
    sessionName: "Beginner Walk-On",
    date: "26 Jan 2026",
    time: "10:00AM - 12:00AM",
    assignStaff: "James Robin",
    matchType: "Social",
    matchTypeColor: "text-emerald-400",
    player: "8/8",
    booked: "2/8",
    price: "$40",
    status: "Booking",
  },
  {
    id: 6,
    sessionName: "Beginner Walk-On",
    date: "26 Jan 2026",
    time: "10:00AM - 12:00AM",
    assignStaff: "James Robin",
    matchType: "Social",
    matchTypeColor: "text-emerald-400",
    player: "8/8",
    booked: "2/8",
    price: "$40",
    status: "Full",
  },
  {
    id: 7,
    sessionName: "Beginner Walk-On",
    date: "26 Jan 2026",
    time: "10:00AM - 12:00AM",
    assignStaff: "James Robin",
    matchType: "Social",
    matchTypeColor: "text-emerald-400",
    player: "8/8",
    booked: "2/8",
    price: "$40",
    status: "Ongoing",
  },
  {
    id: 8,
    sessionName: "Beginner Walk-On",
    date: "26 Jan 2026",
    time: "10:00AM - 12:00AM",
    assignStaff: "James Robin",
    matchType: "Social",
    matchTypeColor: "text-emerald-400",
    player: "8/8",
    booked: "2/8",
    price: "$40",
    status: "Open",
  },
  {
    id: 9,
    sessionName: "Beginner Walk-On",
    date: "26 Jan 2026",
    time: "10:00AM - 12:00AM",
    assignStaff: "James Robin",
    matchType: "Social",
    matchTypeColor: "text-emerald-400",
    player: "8/8",
    booked: "2/8",
    price: "$40",
    status: "Ongoing",
  },
  {
    id: 10,
    sessionName: "Beginner Walk-On",
    date: "26 Jan 2026",
    time: "10:00AM - 12:00AM",
    assignStaff: "James Robin",
    matchType: "Social",
    matchTypeColor: "text-emerald-400",
    player: "8/8",
    booked: "2/8",
    price: "$40",
    status: "Open",
  },
]

export const mockSessionDetail: SessionDetail = {
  id: 1,
  status: "Booking",
  fieldInfo: {
    fieldId: "#CN 256",
    fieldName: "Imrul Hossain",
    location: "Flat 4B, 27 Maple Grove, Birmingham, West Midlands, United State",
    contactNumber: "+26 256 2564",
  },
  sessionInfo: {
    sessionId: "#CN 256",
    sessionName: "Friday Night Colorball Match",
    matchType: "Ranked",
    matchTypeColor: "bg-red-400",
    sessionDate: "25 January, 2026",
    time: "02:30 AM to 03:30 PM",
    sessionType: "Team",
    team: 2,
    playerPerTeam: "8/8",
    packages: "Silver Premium",
  },
  teamInfo: {
    teamAName: "Red Bull Squad",
    teamAScore: 59,
    teamBName: "Snack Green Squad",
    teamBScore: -59,
    champion: "Red Bull Squad",
  },
}
