import type {
  OverviewPageData,
  RevenueOverTimeData,
  SubscriptionChartData,
  DonutChartDataItem,
  CountryRevenueData,
  RecentActivityItem,
  RecentFieldItem,
} from "@/types/AdminTypes/OverviewTypes"
import {
  LayoutGrid,
  Users,
  UserCheck,
  DollarSign,
  CreditCard,
  Home,
  Crown,
  UserPlus,
  AlertCircle,
} from "lucide-react"

export const mockOverviewRevenueOverTime: RevenueOverTimeData[] = [
  { month: "Jan", revenue: 800 },
  { month: "Feb", revenue: 1200 },
  { month: "Mar", revenue: 1500 },
  { month: "Apr", revenue: 1800 },
  { month: "May", revenue: 2200 },
  { month: "Jun", revenue: 3200 },
]

export const mockOverviewSubscriptionChart: SubscriptionChartData[] = [
  { month: "Jan", field: 45000, player: 55000 },
  { month: "Feb", field: 85000, player: 95000 },
  { month: "Mar", field: 50000, player: 70000 },
  { month: "Apr", field: 40000, player: 60000 },
  { month: "May", field: 35000, player: 55000 },
  { month: "Jun", field: 45000, player: 65000 },
]

export const mockSubscriptionDonut: DonutChartDataItem[] = [
  {
    name: "adminAnalytics.gold",
    value: 6700,
    amount: "6,700",
    percentage: "39.2%",
    color: "#EF4444",
  },
  {
    name: "adminAnalytics.silver",
    value: 9302,
    amount: "9,302",
    percentage: "36.1%",
    color: "#EAB308",
  },
  {
    name: "adminAnalytics.bronze",
    value: 3985,
    amount: "3,985",
    percentage: "14.9%",
    color: "#6366F1",
  },
]

export const mockOverviewRevenueByCountry: CountryRevenueData[] = [
  { country: "Span", countryCode: "ES", amount: "\u20AC8,12,450", percentage: "39.2%" },
  { country: "Germany", countryCode: "DE", amount: "\u20AC8,12,450", percentage: "36.1%" },
  { country: "France", countryCode: "FR", amount: "\u20AC8,12,450", percentage: "14.9%" },
  { country: "US", countryCode: "US", amount: "\u20AC8,12,450", percentage: "9.8%" },
  { country: "Ireland", countryCode: "IE", amount: "\u20AC8,12,450", percentage: "9.8%" },
]

export const mockRecentActivity: RecentActivityItem[] = [
  {
    id: 1,
    icon: Home,
    iconColor: "text-emerald-400",
    iconBg: "bg-emerald-500/20",
    title: "adminOverview.paintballMadridApproved",
    description: "adminOverview.paintballMadridDesc",
    time: "5m ago",
  },
  {
    id: 2,
    icon: Crown,
    iconColor: "text-custom-yellow",
    iconBg: "bg-custom-yellow/20",
    title: "adminOverview.newPremiumSubscription",
    description: "adminOverview.newPremiumSubDesc",
    time: "5m ago",
  },
  {
    id: 3,
    icon: UserPlus,
    iconColor: "text-custom-yellow",
    iconBg: "bg-custom-yellow/20",
    title: "adminOverview.newPlayerSubscription",
    description: "adminOverview.newPlayerSubDesc",
    time: "5m ago",
  },
  {
    id: 4,
    icon: AlertCircle,
    iconColor: "text-blue-400",
    iconBg: "bg-blue-500/20",
    title: "adminOverview.newReportReceived",
    description: "adminOverview.newReportDesc",
    time: "5m ago",
  },
]

export const mockRecentFields: RecentFieldItem[] = [
  {
    id: 1,
    fieldName: "adminAnalytics.beginnerPackage",
    fieldId: "FLD-09324",
    description: "adminAnalytics.perfectForFirstTime",
    ownerName: "Kathryn Murphy",
    ownerEmail: "lline@yandex.ru",
    subscription: "Gold",
    countryCode: "ES",
    createdDate: "May 2, 2026",
    createdTime: "10:00 AM",
    booking: 86,
    bookingChange: 18,
    revenue: "\u20AC2,200",
    status: "Approved",
  },
  {
    id: 2,
    fieldName: "adminAnalytics.beginnerPackage",
    fieldId: "FLD-09325",
    description: "adminAnalytics.perfectForFirstTime",
    ownerName: "Wade Warren",
    ownerEmail: "zitka@mail.ru",
    subscription: "Sliver",
    countryCode: "ES",
    createdDate: "May 2, 2026",
    createdTime: "10:00 AM",
    booking: 86,
    bookingChange: 18,
    revenue: "\u20AC2,200",
    status: "Approved",
  },
  {
    id: 3,
    fieldName: "adminAnalytics.beginnerPackage",
    fieldId: "FLD-09326",
    description: "adminAnalytics.perfectForFirstTime",
    ownerName: "Darlene Robertson",
    ownerEmail: "xterris@gmail.com",
    subscription: "Bronze",
    countryCode: "ES",
    createdDate: "May 2, 2026",
    createdTime: "10:00 AM",
    booking: 86,
    bookingChange: 18,
    revenue: "\u20AC2,200",
    status: "Approved",
  },
  {
    id: 4,
    fieldName: "adminAnalytics.beginnerPackage",
    fieldId: "FLD-09327",
    description: "adminAnalytics.perfectForFirstTime",
    ownerName: "Marvin McKinney",
    ownerEmail: "miyokoto@mail.ru",
    subscription: "Gold",
    countryCode: "ES",
    createdDate: "May 2, 2026",
    createdTime: "10:00 AM",
    booking: 86,
    bookingChange: 10,
    revenue: "\u20AC2,200",
    status: "Approved",
  },
  {
    id: 5,
    fieldName: "adminAnalytics.beginnerPackage",
    fieldId: "FLD-09328",
    description: "adminAnalytics.perfectForFirstTime",
    ownerName: "Arlene McCoy",
    ownerEmail: "quasiah@gmail.com",
    subscription: "Bronze",
    countryCode: "ES",
    createdDate: "May 2, 2026",
    createdTime: "10:00 AM",
    booking: 86,
    bookingChange: 18,
    revenue: "\u20AC2,200",
    status: "Approved",
  },
]

export const mockOverviewData: OverviewPageData = {
  stats: [
    {
      title: "adminAnalytics.totalField",
      value: "1243",
      subtitle: "analytics.vsLastMonth",
      change: "+18%",
      icon: LayoutGrid,
    },
    {
      title: "adminAnalytics.totalPlayer",
      value: "9856",
      subtitle: "analytics.vsLastMonth",
      change: "+18%",
      icon: Users,
    },
    {
      title: "adminAnalytics.premiumPlayer",
      value: "2,628",
      subtitle: "analytics.vsLastMonth",
      change: "+18%",
      icon: UserCheck,
    },
    {
      title: "adminAnalytics.totalRevenue",
      value: "\u20AC2,628",
      subtitle: "analytics.vsLastMonth",
      change: "+18%",
      icon: DollarSign,
    },
    {
      title: "adminAnalytics.totalSubscription",
      value: "262",
      subtitle: "analytics.vsLastMonth",
      change: "+18%",
      icon: CreditCard,
    },
  ],
  revenueOverTime: mockOverviewRevenueOverTime,
  subscriptionChart: mockOverviewSubscriptionChart,
  subscriptionDonut: mockSubscriptionDonut,
  revenueByCountry: mockOverviewRevenueByCountry,
  recentActivity: mockRecentActivity,
  recentFields: mockRecentFields,
}
