import type { Subscription } from "@/types/AdminTypes/SubscriptionManagementTypes"

export const mockSubscriptionData: Subscription[] = [
  {
    id: 1,
    subscriber_name: "Beginner Package",
    subscriber_id: "FLD-09324",
    avatar: "",
    type: "Field Owner",
    plan: "Bronze",
    country: "Spain",
    country_code: "ES",
    amount: 2200,
    billing_cycle: "Monthly",
    status: "Active",
    next_billing_date: "May 2, 2026",
  },
  {
    id: 2,
    subscriber_name: "Beginner Package",
    subscriber_id: "FLD-09324",
    avatar: "",
    type: "Field Owner",
    plan: "Premium",
    country: "Spain",
    country_code: "ES",
    amount: 2200,
    billing_cycle: "Yearly",
    status: "Active",
    next_billing_date: "May 2, 2026",
  },
  {
    id: 3,
    subscriber_name: "Beginner Package",
    subscriber_id: "FLD-09324",
    avatar: "",
    type: "Player",
    plan: "Premium",
    country: "Spain",
    country_code: "ES",
    amount: 2200,
    billing_cycle: "Monthly",
    status: "Trial",
    next_billing_date: "May 2, 2026",
  },
  {
    id: 4,
    subscriber_name: "Beginner Package",
    subscriber_id: "FLD-09324",
    avatar: "",
    type: "Field Owner",
    plan: "Silver",
    country: "Spain",
    country_code: "ES",
    amount: 2200,
    billing_cycle: "Yearly",
    status: "Active",
    next_billing_date: "May 2, 2026",
  },
  {
    id: 5,
    subscriber_name: "Beginner Package",
    subscriber_id: "FLD-09324",
    avatar: "",
    type: "Player",
    plan: "Premium",
    country: "Spain",
    country_code: "ES",
    amount: 2200,
    billing_cycle: "Monthly",
    status: "Trial",
    next_billing_date: "May 2, 2026",
  },
  {
    id: 6,
    subscriber_name: "Beginner Package",
    subscriber_id: "FLD-09324",
    avatar: "",
    type: "Field Owner",
    plan: "Gold",
    country: "Spain",
    country_code: "ES",
    amount: 2200,
    billing_cycle: "Yearly",
    status: "Active",
    next_billing_date: "May 2, 2026",
  },
  {
    id: 7,
    subscriber_name: "Beginner Package",
    subscriber_id: "FLD-09324",
    avatar: "",
    type: "Field Owner",
    plan: "Silver",
    country: "Spain",
    country_code: "ES",
    amount: 2200,
    billing_cycle: "Yearly",
    status: "Past Due",
    next_billing_date: "May 2, 2026",
  },
  {
    id: 8,
    subscriber_name: "Beginner Package",
    subscriber_id: "FLD-09324",
    avatar: "",
    type: "Field Owner",
    plan: "Gold",
    country: "Spain",
    country_code: "ES",
    amount: 2200,
    billing_cycle: "Monthly",
    status: "Active",
    next_billing_date: "May 2, 2026",
  },
  {
    id: 9,
    subscriber_name: "Beginner Package",
    subscriber_id: "FLD-09324",
    avatar: "",
    type: "Player",
    plan: "Premium",
    country: "Spain",
    country_code: "ES",
    amount: 2200,
    billing_cycle: "Yearly",
    status: "Active",
    next_billing_date: "May 2, 2026",
  },
  {
    id: 10,
    subscriber_name: "Beginner Package",
    subscriber_id: "FLD-09324",
    avatar: "",
    type: "Field Owner",
    plan: "Bronze",
    country: "Spain",
    country_code: "ES",
    amount: 2200,
    billing_cycle: "Monthly",
    status: "Active",
    next_billing_date: "May 2, 2026",
  },
  {
    id: 11,
    subscriber_name: "Pro Package",
    subscriber_id: "FLD-09325",
    avatar: "",
    type: "Player",
    plan: "Premium",
    country: "Spain",
    country_code: "ES",
    amount: 2200,
    billing_cycle: "Monthly",
    status: "Trial",
    next_billing_date: "May 2, 2026",
  },
  {
    id: 12,
    subscriber_name: "Pro Package",
    subscriber_id: "FLD-09325",
    avatar: "",
    type: "Field Owner",
    plan: "Gold",
    country: "Spain",
    country_code: "ES",
    amount: 2200,
    billing_cycle: "Yearly",
    status: "Active",
    next_billing_date: "May 2, 2026",
  },
  {
    id: 13,
    subscriber_name: "Pro Package",
    subscriber_id: "FLD-09325",
    avatar: "",
    type: "Player",
    plan: "Premium",
    country: "Spain",
    country_code: "ES",
    amount: 2200,
    billing_cycle: "Yearly",
    status: "Active",
    next_billing_date: "May 2, 2026",
  },
  {
    id: 14,
    subscriber_name: "Pro Package",
    subscriber_id: "FLD-09325",
    avatar: "",
    type: "Field Owner",
    plan: "Silver",
    country: "Spain",
    country_code: "ES",
    amount: 2200,
    billing_cycle: "Monthly",
    status: "Past Due",
    next_billing_date: "May 2, 2026",
  },
  {
    id: 15,
    subscriber_name: "Pro Package",
    subscriber_id: "FLD-09325",
    avatar: "",
    type: "Player",
    plan: "Premium",
    country: "Spain",
    country_code: "ES",
    amount: 2200,
    billing_cycle: "Monthly",
    status: "Active",
    next_billing_date: "May 2, 2026",
  },
  {
    id: 16,
    subscriber_name: "Pro Package",
    subscriber_id: "FLD-09325",
    avatar: "",
    type: "Field Owner",
    plan: "Gold",
    country: "Spain",
    country_code: "ES",
    amount: 2200,
    billing_cycle: "Yearly",
    status: "Active",
    next_billing_date: "May 2, 2026",
  },
  {
    id: 17,
    subscriber_name: "Elite Package",
    subscriber_id: "FLD-09326",
    avatar: "",
    type: "Player",
    plan: "Premium",
    country: "Spain",
    country_code: "ES",
    amount: 2200,
    billing_cycle: "Monthly",
    status: "Trial",
    next_billing_date: "May 2, 2026",
  },
  {
    id: 18,
    subscriber_name: "Elite Package",
    subscriber_id: "FLD-09326",
    avatar: "",
    type: "Field Owner",
    plan: "Bronze",
    country: "Spain",
    country_code: "ES",
    amount: 2200,
    billing_cycle: "Yearly",
    status: "Active",
    next_billing_date: "May 2, 2026",
  },
  {
    id: 19,
    subscriber_name: "Elite Package",
    subscriber_id: "FLD-09326",
    avatar: "",
    type: "Player",
    plan: "Premium",
    country: "Spain",
    country_code: "ES",
    amount: 2200,
    billing_cycle: "Yearly",
    status: "Active",
    next_billing_date: "May 2, 2026",
  },
  {
    id: 20,
    subscriber_name: "Elite Package",
    subscriber_id: "FLD-09326",
    avatar: "",
    type: "Field Owner",
    plan: "Silver",
    country: "Spain",
    country_code: "ES",
    amount: 2200,
    billing_cycle: "Monthly",
    status: "Active",
    next_billing_date: "May 2, 2026",
  },
]
